# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command/command.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15\x63ommand/command.proto\x12\x12mavsdk.rpc.command"J\n\x16SendCommandLongRequest\x12\x30\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x1f.mavsdk.rpc.command.CommandLong"\xd5\x01\n\x0b\x43ommandLong\x12\x15\n\rtarget_system\x18\x01 \x01(\r\x12\x18\n\x10target_component\x18\x02 \x01(\r\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\r\x12\x14\n\x0c\x63onfirmation\x18\x04 \x01(\r\x12\x0e\n\x06param1\x18\x05 \x01(\x02\x12\x0e\n\x06param2\x18\x06 \x01(\x02\x12\x0e\n\x06param3\x18\x07 \x01(\x02\x12\x0e\n\x06param4\x18\x08 \x01(\x02\x12\x0e\n\x06param5\x18\t \x01(\x02\x12\x0e\n\x06param6\x18\n \x01(\x02\x12\x0e\n\x06param7\x18\x0b \x01(\x02"T\n\x17SendCommandLongResponse\x12\x39\n\x0e\x63ommand_result\x18\x01 \x01(\x0b\x32!.mavsdk.rpc.command.CommandResult"\xa0\x02\n\rCommandResult\x12\x38\n\x06result\x18\x01 \x01(\x0e\x32(.mavsdk.rpc.command.CommandResult.Result\x12\x12\n\nresult_str\x18\x02 \x01(\t"\xc0\x01\n\x06Result\x12\x13\n\x0fRESULT_ACCEPTED\x10\x00\x12\x1f\n\x1bRESULT_TEMPORARILY_REJECTED\x10\x01\x12\x11\n\rRESULT_DENIED\x10\x02\x12\x16\n\x12RESULT_UNSUPPORTED\x10\x03\x12\x11\n\rRESULT_FAILED\x10\x04\x12\x16\n\x12RESULT_IN_PROGRESS\x10\x05\x12\x14\n\x10RESULT_CANCELLED\x10\x06\x12\x14\n\x10RESULT_NO_SYSTEM\x10\x07\x32~\n\x0e\x43ommandService\x12l\n\x0fSendCommandLong\x12*.mavsdk.rpc.command.SendCommandLongRequest\x1a+.mavsdk.rpc.command.SendCommandLongResponse"\x00\x42!\n\x11io.mavsdk.commandB\x0c\x43ommandProtob\x06proto3'
)


_SENDCOMMANDLONGREQUEST = DESCRIPTOR.message_types_by_name["SendCommandLongRequest"]
_COMMANDLONG = DESCRIPTOR.message_types_by_name["CommandLong"]
_SENDCOMMANDLONGRESPONSE = DESCRIPTOR.message_types_by_name["SendCommandLongResponse"]
_COMMANDRESULT = DESCRIPTOR.message_types_by_name["CommandResult"]
_COMMANDRESULT_RESULT = _COMMANDRESULT.enum_types_by_name["Result"]
SendCommandLongRequest = _reflection.GeneratedProtocolMessageType(
    "SendCommandLongRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _SENDCOMMANDLONGREQUEST,
        "__module__": "command.command_pb2"
        # @@protoc_insertion_point(class_scope:mavsdk.rpc.command.SendCommandLongRequest)
    },
)
_sym_db.RegisterMessage(SendCommandLongRequest)

CommandLong = _reflection.GeneratedProtocolMessageType(
    "CommandLong",
    (_message.Message,),
    {
        "DESCRIPTOR": _COMMANDLONG,
        "__module__": "command.command_pb2"
        # @@protoc_insertion_point(class_scope:mavsdk.rpc.command.CommandLong)
    },
)
_sym_db.RegisterMessage(CommandLong)

SendCommandLongResponse = _reflection.GeneratedProtocolMessageType(
    "SendCommandLongResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _SENDCOMMANDLONGRESPONSE,
        "__module__": "command.command_pb2"
        # @@protoc_insertion_point(class_scope:mavsdk.rpc.command.SendCommandLongResponse)
    },
)
_sym_db.RegisterMessage(SendCommandLongResponse)

CommandResult = _reflection.GeneratedProtocolMessageType(
    "CommandResult",
    (_message.Message,),
    {
        "DESCRIPTOR": _COMMANDRESULT,
        "__module__": "command.command_pb2"
        # @@protoc_insertion_point(class_scope:mavsdk.rpc.command.CommandResult)
    },
)
_sym_db.RegisterMessage(CommandResult)

_COMMANDSERVICE = DESCRIPTOR.services_by_name["CommandService"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\021io.mavsdk.commandB\014CommandProto"
    _SENDCOMMANDLONGREQUEST._serialized_start = 45
    _SENDCOMMANDLONGREQUEST._serialized_end = 119
    _COMMANDLONG._serialized_start = 122
    _COMMANDLONG._serialized_end = 335
    _SENDCOMMANDLONGRESPONSE._serialized_start = 337
    _SENDCOMMANDLONGRESPONSE._serialized_end = 421
    _COMMANDRESULT._serialized_start = 424
    _COMMANDRESULT._serialized_end = 712
    _COMMANDRESULT_RESULT._serialized_start = 520
    _COMMANDRESULT_RESULT._serialized_end = 712
    _COMMANDSERVICE._serialized_start = 714
    _COMMANDSERVICE._serialized_end = 840
# @@protoc_insertion_point(module_scope)
